allowBuilds:
  esbuild: true
  rollup: true
  cookie: true
  content-type: true
  pathval: true
  pino-abstract-transport: true
  ret: true
  tinyexec: true
  tinyspy: true
onlyBuiltDependencies:
  - esbuild
  - rollup
  - cookie
  - content-type
  - pathval
  - pino-abstract-transport
  - ret
  - tinyexec
  - tinyspy
